spring:
  jpa:
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.mailgun.org
    username: letsconnect@sandbox916f5d7f77f3464085b6f7562e1a4c8b.mailgun.org

jwt:
  expiration-minutes: 1000

nginx:
  require-proxy: false

letsconnect:
  email:
    url: "http://localhost:8080"
  rate-limit:
    ip:
      apply-limit: false
